#!/usr/bin/env bash
# this is factors challenge

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                cont=0
                nmb2=1
                for a in ${args[*]};
                do
                        if [ $cont -gt 1 ];
                        then
                                nmb2=$(echo $a*$nmb2 | bc)
                        fi
                        cont=$((cont + 1))
                done
        else
                nmb2=$3
        fi

        nmb1=$2
        nmb=$(echo "$1" | tr ':' '=')

        resut=$(echo "if($nmb2 > $nmb1) 1 else 0" | bc)
	        if ((resut == 1)); then
		        nmbcp=$nmb1
		        nmb1=$nmb2
		        nmb2=$nmbcp
                fi

        echo "$nmb$nmb1*$nmb2"
}

	if [ $# -ne 1 ]
	then
        	echo 'Usage: factors <file>'
        	exit 1
	else

        	while read i
        	do

                	resut=$(factor "$i")
                	check_factor $resut

        	done < "$1"
	fi
